### ISSUE TITLE
Undesired code block line height under edit mode

### ISSUE THREAD

**Issue by SPiCaRiA** [Bluemoondragon07/obsidian-notation-2#2]
Hi,

It seems that the code block lines have undesired line height under the edit mode:

<img width="739" alt="Screen Shot 2023-03-25 at 17 55 54" src="https://user-images.githubusercontent.com/11176415/227749465-77e70933-fe77-4e51-b4f0-abbadd822e81.png">

This is caused by the top/bottom padding of the line `div`s under the code mirror editor.

<img width="221" alt="Screen Shot 2023-03-25 at 17 58 20" src="https://user-images.githubusercontent.com/11176415/227749526-9c2cc6b7-fc56-4107-b649-b823881aef3b.png">

I haven't gone through the theme file yet so I won't be able to create a PR without screwing up the codes :( But I guess the quickfix is to just remove the top/bottom paddings on all `div.HyperMD-codeblock` elements.

Thanks for making this great theme!

**Comment by Bluemoondragon07** [comment]
Fixed! Enjoy.
