### ISSUE TITLE
Absolute positioning of the "New Page" button blocking the file explorer

### ISSUE THREAD

**Issue by SPiCaRiA** [Bluemoondragon07/obsidian-notation-2#4]
Hi,

It seems that the file explorer entries at the bottom will be blocked by the "New Page" button:

**Expected**
<img width="339" alt="Screen Shot 2023-03-26 at 14 17 11" src="https://user-images.githubusercontent.com/11176415/227805090-c45ac75e-2bc2-4e6e-8057-8bff550cc183.png">

**Actual** (can't see the "zplaceholder2.md" file)
<img width="355" alt="Screen Shot 2023-03-26 at 14 16 43" src="https://user-images.githubusercontent.com/11176415/227805069-9d68d6fc-be07-4153-8216-6bf2bb0d6f0e.png">

I guess this is caused by the absolute positioning of the "New Page" button. IMHO, we can set the `flex-direction: column-reverse` property of the `div.workspace-leaf-content` element instead, which simply reverse the order of the nav header and the nav content in a cleaner way. The "expected" screenshot above was captured on my patch snippets with this approach, and it does what we want. :)

Please let me know how you think about this, thanks!

**Comment by Bluemoondragon07** [comment]
Thank you for your suggestion. I think your method is much better than mine! It might be a while (I'm busy with school right now) but I will definitely fix this along with #2 and #3. Thanks for pointing these out!
