### ISSUE TITLE
Scrolling doesn't work

### ISSUE THREAD

**Issue by rockofox** [Bluemoondragon07/obsidian-notation-2#7]
After enabling the theme, I can't scroll in my notes anymore.

I am running the newest version of Obsidian on macOS.

**Comment by Bluemoondragon07** [comment]
Do you have native scrollbars enabled on your system?

**Comment by rockofox** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/5049120/231171137-711d154f-7bd2-4872-bf08-e4546eddc8d8.png">
I don't know if that's what you mean, but I've tried all those settings in the macOS preferences application if you mean that, but they don't seem to have an influence on the problem. 
<br/><br/>
 
Interestingly, I am able to "fix" this problem and restore my ability to scroll by disabling "WYSIWYG Effect" in the theme's settings. I don't really care about this setting anyway, so I will just keep it disabled, but that seems to be where the culprit is.
<img width="756" alt="image" src="https://user-images.githubusercontent.com/5049120/231171477-21557e70-6e24-4ec1-a237-9c4f46a954be.png">

**Comment by Bluemoondragon07** [comment]
That's interesting. I'm guessing that has something to do with modifying the `<br>` element, but I'm not sure why that would affect scrolling. Anyhow, I'll clean up the "WYSIWYG" code (I was mostly just experimenting when I made it) and hopefully that fixes it for other users. Glad you found a current solution.

**Comment by rockofox** [comment]
Hmmm, but I just noticed that if I turn off WYSIWYG Effect, empty lines are not shown, which is pretty weird.
The screenshots below show the same note.

**WYSIWYG Effect off**: <img width="2167" alt="image" src="https://user-images.githubusercontent.com/5049120/231177185-e9ce3ea4-ca47-470a-b0b6-d0de55a0d297.png">

**WYSIWYG Effect on**: <img width="2170" alt="image" src="https://user-images.githubusercontent.com/5049120/231177228-b6e057d9-41eb-4c47-85d1-0b6c53fd7e9f.png">


(the on version is how I would expect it to show the note, and how other themes show it)

**Comment by rockofox** [comment]
Oh, I just randomly found an description what WYSIWYG mode is supposed to do you wrote (https://github.com/Bluemoondragon07/Obsidian-amazing-snippets/blob/main/For%20Theme%20Development/WYSIWYG%20Effect.md) and apparently it is supposed to hide empty lines. So the setting is reversed?

**Comment by Bluemoondragon07** [comment]
Huh. I guess I did reverse it. I'll fix that!

**Comment by aseth0** [comment]
Hello, 
have you any updates about this?
your theme is the best that I found according to my requirements  but this issue is very annoying  :(
greetings!

**Comment by Bluemoondragon07** [comment]
I just updated the theme a few minutes ago, and the scrolling should now be fixed. Sorry about the wait! At this point, I have like, five different themes, so it's getting kind of hard to keep track of all of them. 

Anyway, enjoy the update 🙂
