### ISSUE TITLE
Sort function missing

### ISSUE THREAD

**Issue by dreinert1** [Bluemoondragon07/obsidian-notation-2#8]
Hey man, theme looks great and all but after hours of investigating to find out where the file sort function went I realized it was because this theme removes it.  Was driving me mad for a good while. Definitely add disclaimer in the docs and fix that asap. Otherwise it's a great theme.

**Comment by Bluemoondragon07** [comment]
Thanks for pointing this out. In the new update, all navigation buttons, including Sort, are visible by default. Thanks for helping me prevent confusion for future users 🙂
